name: monitoring-kube-state-metrics
title: Monitoring kube-state-metrics
type: infrastructure
scalable: false
hostname: kube-state-metrics
containers:
- name: kube-state-metrics
  resources:
    request:
      memory: 128
      cpu: 100
