name: monitoring-kube-state-metrics
title: Monitoring kube-state-metrics
type: infrastructure
scalable: false
containers:
  - name: kube-state-metrics
    resources:
      limit:
        cpu: 200
        memory: 200
