apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kube-state-metrics
  labels:
    name: kube-state-metrics
spec:
  selector:
    name: kube-state-metrics
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
  clusterIP: None
